comment: false

codecov:
  token: 2230322b-9ed3-493a-8c79-7b608438c304

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto
        threshold: 1%
